<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'DejaVu Sans', sans-serif;
    padding: 40px;
    color: #1a1a1a;
  }
  .header {
    background: linear-gradient(135deg, #7C3AED, #EC4899);
    color: white;
    padding: 30px;
    border-radius: 12px;
    margin-bottom: 30px;
  }
  .header h1 { font-size: 26px; margin-bottom: 6px; }
  .header p  { font-size: 13px; opacity: 0.85; }
  .section { margin-bottom: 24px; }
  .section h2 {
    font-size: 15px;
    color: #7C3AED;
    border-bottom: 2px solid #f0e6ff;
    padding-bottom: 6px;
    margin-bottom: 14px;
    text-transform: uppercase;
  }
  .info-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 10px;
  }
  .info-box {
    background: #f8f4ff;
    padding: 12px;
    border-radius: 8px;
  }
  .info-box .label { font-size: 11px; color: #888; }
  .info-box .value { font-size: 14px; font-weight: bold; color: #333; }
  .finding-box {
    background: #fafafa;
    border: 1px solid #eee;
    border-radius: 8px;
    padding: 16px;
    margin-bottom: 10px;
  }
  .finding-box h3 { font-size: 13px; color: #7C3AED; margin-bottom: 6px; }
  .finding-box p  { font-size: 13px; color: #555; line-height: 1.6; }
  .recommendation {
    background: #f0fdf4;
    border-left: 4px solid #059669;
    padding: 14px 18px;
    border-radius: 8px;
    margin-bottom: 10px;
  }
  .recommendation p { font-size: 13px; color: #555; line-height: 1.6; }
  .footer {
    margin-top: 40px;
    text-align: center;
    color: #aaa;
    font-size: 11px;
    border-top: 1px solid #eee;
    padding-top: 16px;
  }
</style>
</head>
<body>

  <div class="header">
    <h1>🌸 Health Consultation Report</h1>
    <p>Prepared by Rakhi AI Health Coach &bull; {{ $date }}</p>
  </div>

  <!-- Profile -->
  <div class="section">
    <h2>User Profile</h2>
    <div class="info-grid">
      @foreach([
        ['Name',       $user->first_name . ' ' . $user->last_name],
        ['Age',        $user->age() . ' years'],
        ['Gender',     ucfirst($user->gender ?? '—')],
        ['Weight',     ($user->weight ?? '—') . ' kg'],
        ['Height',     ($user->height ?? '—') . ' cm'],
        ['Diet',       ucfirst($user->diet_preference ?? '—')],
        ['Stress',     ucfirst($user->stress_level ?? '—')],
        ['Sleep',      ($user->sleep_hours ?? '—') . ' hrs/night'],
        ['Activity',   ucfirst($user->activity_level ?? '—')],
      ] as [$label, $value])
      <div class="info-box">
        <div class="label">{{ $label }}</div>
        <div class="value">{{ $value }}</div>
      </div>
      @endforeach
    </div>
  </div>

  <!-- Goals -->
  <div class="section">
    <h2>Health Goals</h2>
    @foreach($user->goals as $goal)
      <span style="display:inline-block; background:#f0e6ff;
                   color:#7C3AED; padding:4px 12px; border-radius:20px;
                   font-size:12px; margin:3px;">
        {{ $goal->name }}
      </span>
    @endforeach
  </div>

  <!-- Findings -->
  @if(isset($report['findings']))
  <div class="section">
    <h2>Key Findings</h2>
    @foreach($report['findings'] as $finding)
    <div class="finding-box">
      <h3>{{ $finding['area'] ?? '' }}</h3>
      <p>{{ $finding['observation'] ?? '' }}</p>
    </div>
    @endforeach
  </div>
  @endif

  <!-- Recommendations -->
  @if(isset($report['recommendations']))
  <div class="section">
    <h2>Recommendations</h2>
    @foreach($report['recommendations'] as $rec)
    <div class="recommendation">
      <p>✅ {{ $rec }}</p>
    </div>
    @endforeach
  </div>
  @endif

  <!-- Next Steps -->
  @if(isset($report['next_steps']))
  <div class="section">
    <h2>Next Steps</h2>
    @foreach($report['next_steps'] as $step)
    <div style="background:#fff8e1; border-left:4px solid #F59E0B;
                padding:12px 16px; border-radius:8px; margin-bottom:8px;">
      <p style="font-size:13px; color:#555;">→ {{ $step }}</p>
    </div>
    @endforeach
  </div>
  @endif

  <div class="footer">
    <p>
      This report is generated by Rakhi AI for lifestyle and
      wellness guidance only. It does not constitute medical advice.
      Please consult a qualified healthcare professional for
      medical decisions.
    </p>
    <p style="margin-top:6px;">
      🌸 Rakhi AI &bull; rakhi.ai &bull; {{ $date }}
    </p>
  </div>

</body>
</html>
